Module2 task1
htmlacademy-ecmascript/1401569-big-trip-14 pull request #4
Opened 2021-05-04 14:27 UTC by AlexeySlyusarenko

2021-05-06 19:01 UTC, Epsilonnnn requested changes

2021-05-06 19:01 UTC, Epsilonnnn commented on src/const/data-event.js
> +const Event = {
кажется, это нигде не нужно?

2021-05-07 05:09 UTC, AlexeySlyusarenko commented on src/mocks/mock-city.js
> +    result[result.length - 1] = result[result.length - 1].slice(0, -1);
Если убрать
result[result.length - 1] = result[result.length - 1].slice(0, -1);
то появиться дополнительная точка в описании

2021-05-07 05:56 UTC, AlexeySlyusarenko commented on src/mocks/mock-point.js
> +      start: start.toISOString(),
в этом месте я имитировал данные с сервера, а в функции datePoint() я преобразую эти данные в объект дата.

2021-05-08 20:34 UTC, Epsilonnnn commented on src/view/trip.js
> +  points.forEach((point) => {
reduce?

2021-05-08 20:34 UTC, Epsilonnnn commented on src/mocks/mock.js
> +CITY_LIST.forEach((value) => {
map?

`export const mockCities = CITY_LIST.map((value) => ...);`

2021-05-08 20:34 UTC, Epsilonnnn commented on src/mocks/mock.js
> +TYPE_LIST.forEach((value) => {
map?

2021-05-08 20:34 UTC, Epsilonnnn commented on src/mocks/mock-point.js
> +      start: start.toISOString(),
да, в целом это правильно, но я к тому, что сравнивать даты таким образом  https://github.com/htmlacademy-ecmascript/1401569-big-trip-14/pull/4/files#diff-cd848e15ae36f0d06d38dd84247b7a375ab54c5d432d38acaf8e77009e586450R83 не очень правильно:

1. реплейс в строчках чего-то
2. нет приведения в числа и они сравниваются как строчки как минимум при `===`

2021-05-08 20:40 UTC, Epsilonnnn requested changes

2021-05-08 20:40 UTC, Epsilonnnn commented on src/view/trip.js
> +  while (i < points.length - 1) {
не поправлено)

2021-05-12 18:54 UTC, merged